apiVersion: v1
kind: Secret
metadata:
  name: todo-secret

type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  username: cm9vdA==
  password: cGFzc3dvcmQ=